-- =============================================================
-- SPELBOK — Cron för automatisk sättling
--
-- Schemalägger Edge-funktionen settle-bets var 15:e minut.
-- Funktionen hämtar resultat från API-Football, uppdaterar
-- fixtures-cachen, rättar spel som går att maskinläsa och lägger
-- resten i settle_queue (syns i /admin/sattling).
--
-- ORDNING:
--   1. Deploya funktionen och sätt nyckeln:
--        supabase functions deploy settle-bets
--        supabase secrets set APIFOOTBALL_KEY=din-nyckel
--   2. Aktivera extensions i Dashboard > Database > Extensions:
--        pg_cron, pg_net
--   3. Fyll i PROJEKT_REF och SERVICE_ROLE_KEY nedan.
--   4. Avkommentera och kör blocket i SQL Editor.
--
-- OBS: service role-nyckeln hamnar i cron.job-tabellen i klartext.
--      Lägg den i Vault om du vill undvika det (se längst ner).
-- =============================================================

-- -------------------------------------------------------------
-- 1. Extensions (kan även aktiveras via Dashboard)
-- -------------------------------------------------------------
-- create extension if not exists pg_cron with schema pg_catalog;
-- create extension if not exists pg_net;

-- -------------------------------------------------------------
-- 2. Schemalägg var 15:e minut
--    Cron-uttryck: minut 0, 15, 30 och 45 varje timme.
-- -------------------------------------------------------------
-- select cron.schedule(
--   'settle-bets-var-15-min',
--   '*/15 * * * *',
--   $$
--   select net.http_post(
--     url     := 'https://PROJEKT_REF.supabase.co/functions/v1/settle-bets',
--     headers := jsonb_build_object(
--       'Content-Type',  'application/json',
--       'Authorization', 'Bearer SERVICE_ROLE_KEY'
--     ),
--     body    := '{}'::jsonb,
--     timeout_milliseconds := 55000
--   );
--   $$
-- );

-- -------------------------------------------------------------
-- 3. Kontrollera
-- -------------------------------------------------------------
-- Alla schemalagda jobb:
--   select jobid, jobname, schedule, active from cron.job;
--
-- Senaste körningarna (status, svarstid, eventuellt fel):
--   select jobid, status, return_message, start_time, end_time
--   from cron.job_run_details
--   order by start_time desc
--   limit 20;
--
-- Svaren från Edge-funktionen (pg_net loggar HTTP-svaret):
--   select id, status_code, content, created
--   from net._http_response
--   order by created desc
--   limit 20;

-- -------------------------------------------------------------
-- 4. Pausa / ta bort
-- -------------------------------------------------------------
-- update cron.job set active = false where jobname = 'settle-bets-var-15-min';
-- select cron.unschedule('settle-bets-var-15-min');

-- -------------------------------------------------------------
-- 5. Frivilligt: nyckeln i Vault istället för i klartext
-- -------------------------------------------------------------
-- select vault.create_secret('SERVICE_ROLE_KEY', 'settle_bets_key');
--
-- select cron.schedule(
--   'settle-bets-var-15-min',
--   '*/15 * * * *',
--   $$
--   select net.http_post(
--     url     := 'https://PROJEKT_REF.supabase.co/functions/v1/settle-bets',
--     headers := jsonb_build_object(
--       'Content-Type',  'application/json',
--       'Authorization', 'Bearer ' || (
--         select decrypted_secret from vault.decrypted_secrets
--         where name = 'settle_bets_key'
--       )
--     ),
--     body    := '{}'::jsonb,
--     timeout_milliseconds := 55000
--   );
--   $$
-- );

-- =============================================================
-- Testa funktionen manuellt utan att skriva något:
--   curl -i -X POST \
--     -H "Authorization: Bearer SERVICE_ROLE_KEY" \
--     "https://PROJEKT_REF.supabase.co/functions/v1/settle-bets?dry=1"
--
-- Svaret ser ut så här:
--   {"checked":12,"updated":12,"settled":9,"queued":1,"dryRun":true,"ms":842}
-- =============================================================
