-- =============================================================
-- SPELBOK — Cron för fixtures-synk och automatisk sättling
--
-- Schemalägger:
--   sync-fixtures   05:00 Europe/Stockholm (1 gång/dygn)
--   settle-results  var 15:e minut
--
-- Båda anropas via pg_net mot Edge Function-URL:erna med
-- service role-nyckel i Authorization. Nyckeln till API-Sports
-- ligger i Edge Function secrets, inte i cron-jobbet.
--
-- ORDNING:
--   1. Kör db/apisports-migration.sql
--   2. Deploya funktionerna och sätt secrets:
--        supabase functions deploy sync-fixtures
--        supabase functions deploy settle-results
--        supabase secrets set APISPORTS_KEY=din-nyckel
--        supabase secrets set APISPORTS_FOOTBALL_URL=https://v3.football.api-sports.io
--   3. Aktivera extensions i Dashboard > Database > Extensions:
--        pg_cron, pg_net
--   4. Fyll i PROJEKT_REF och SERVICE_ROLE_KEY nedan.
--   5. Avkommentera och kör blocken i SQL Editor.
--
-- OBS: service role-nyckeln hamnar i cron.job i klartext.
--      Använd Vault-varianten längst ner om du vill undvika det.
--
-- Tidzon: pg_cron kör i UTC om cron.timezone inte är satt.
-- 05:00 Stockholm = 03:00 UTC sommartid, 04:00 UTC vintertid.
-- Sätt hellre cron.timezone (kräver rätt behörighet):
--   alter database postgres set cron.timezone = 'Europe/Stockholm';
-- =============================================================

-- -------------------------------------------------------------
-- 1. Extensions
-- -------------------------------------------------------------
-- create extension if not exists pg_cron with schema pg_catalog;
-- create extension if not exists pg_net;

-- -------------------------------------------------------------
-- 2. sync-fixtures — varje natt 03:00 UTC ≈ 05:00 Stockholm
-- -------------------------------------------------------------
-- select cron.unschedule('sync-fixtures-daily');
-- select cron.schedule(
--   'sync-fixtures-daily',
--   '0 3 * * *',
--   $$
--   select net.http_post(
--     url     := 'https://PROJEKT_REF.supabase.co/functions/v1/sync-fixtures',
--     headers := jsonb_build_object(
--       'Content-Type',  'application/json',
--       'Authorization', 'Bearer SERVICE_ROLE_KEY'
--     ),
--     body    := '{}'::jsonb,
--     timeout_milliseconds := 120000
--   );
--   $$
-- );

-- -------------------------------------------------------------
-- 3. settle-results — var 15:e minut
--    Funktionen avslutar utan API-anrop när inget behöver settlas.
-- -------------------------------------------------------------
-- select cron.unschedule('settle-bets-var-15-min');
-- select cron.unschedule('settle-results-var-15-min');
-- select cron.schedule(
--   'settle-results-var-15-min',
--   '*/15 * * * *',
--   $$
--   select net.http_post(
--     url     := 'https://PROJEKT_REF.supabase.co/functions/v1/settle-results',
--     headers := jsonb_build_object(
--       'Content-Type',  'application/json',
--       'Authorization', 'Bearer SERVICE_ROLE_KEY'
--     ),
--     body    := '{}'::jsonb,
--     timeout_milliseconds := 55000
--   );
--   $$
-- );

-- -------------------------------------------------------------
-- 4. Kontrollera
-- -------------------------------------------------------------
-- select jobid, jobname, schedule, active from cron.job;
--
-- select jobid, status, return_message, start_time, end_time
-- from cron.job_run_details
-- order by start_time desc
-- limit 20;
--
-- select id, status_code, content, created
-- from net._http_response
-- order by created desc
-- limit 20;
--
-- Senaste synkar:
--   select job, ok, requests, upserted, settled, error, started_at
--   from public.sync_log
--   order by started_at desc
--   limit 20;

-- -------------------------------------------------------------
-- 5. Pausa / ta bort
-- -------------------------------------------------------------
-- update cron.job set active = false where jobname in (
--   'sync-fixtures-daily',
--   'settle-results-var-15-min',
--   'settle-bets-var-15-min'
-- );
-- select cron.unschedule('sync-fixtures-daily');
-- select cron.unschedule('settle-results-var-15-min');

-- -------------------------------------------------------------
-- 6. Frivilligt: nyckeln i Vault
-- -------------------------------------------------------------
-- select vault.create_secret('SERVICE_ROLE_KEY', 'edge_functions_key');
--
-- select cron.schedule(
--   'sync-fixtures-daily',
--   '0 3 * * *',
--   $$
--   select net.http_post(
--     url     := 'https://PROJEKT_REF.supabase.co/functions/v1/sync-fixtures',
--     headers := jsonb_build_object(
--       'Content-Type',  'application/json',
--       'Authorization', 'Bearer ' || (
--         select decrypted_secret from vault.decrypted_secrets
--         where name = 'edge_functions_key'
--       )
--     ),
--     body    := '{}'::jsonb,
--     timeout_milliseconds := 120000
--   );
--   $$
-- );

-- =============================================================
-- Testa manuellt:
--   curl -i -X POST \
--     -H "Authorization: Bearer SERVICE_ROLE_KEY" \
--     "https://PROJEKT_REF.supabase.co/functions/v1/sync-fixtures"
--
--   curl -i -X POST \
--     -H "Authorization: Bearer SERVICE_ROLE_KEY" \
--     "https://PROJEKT_REF.supabase.co/functions/v1/settle-results?dry=1"
-- =============================================================
